modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"

[[mods]]
modId = "globalcontrols"
version = "1.0.0"
displayName = "GlobalControls"
description = "Global keybind profile across modpacks"
