modLoader = "javafml"
loaderVersion = "[48,)"
license = "GPL-3.0"

[[mods]]
modId = "globalcontrols"
version = "1.0.1"
displayName = "GlobalControls"
description = "Global keybind profile across modpacks"
